name: couldai_user_app
description: "App escáner para Ministerio del Poder Popular para ADULTOS MAYORES"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.1.1  # Para escaneo QR con acceso a cámara y permisos
  intl: ^0.19.0  # Para manejo de fechas y formato
  provider: ^6.1.2  # Para gestión de estado simple (opcional, para simular datos)
  image_picker: ^1.1.2 # Para seleccionar imágenes de la galería

# Nota: Para backend Supabase, conecta primero antes de agregar supabase_flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Agrega assets si necesitas imágenes (e.g., íconos para módulos)
  # assets:
  #   - assets/images/
